# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [136]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

arr_height = np.array(height)
arr_weight = np.array(weight)

bmi = arr_weight / (arr_height ** 2) * 730
y = 1
for i in bmi:
    print(f'BMI #{y}: {i}')
    y += 1
    

BMI #1: 16.866204578869986
BMI #2: 17.877551020408163
BMI #3: 18.825629835350128
BMI #4: 19.714506172839506
BMI #5: 20.54794520547945
BMI #6: 21.329437545653764
BMI #7: 22.06222222222222


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [139]:
# Create a function that will take in two parameters and will create a random matrix based off of those paramters.
def my_func_1(row_num, col_num):
    i = np.random.random((row_num, col_num))
    j = np.matrix(i)
    print('\n',j)
 
my_func_1(2,4)


# Extra: Have additional paramters taken in that allow the user to choose the shape and data type of the matrix.
def my_func_2(rand_num_low, rand_num_high, row_num, col_num, data_type):
    i = np.random.uniform(rand_num_low, rand_num_high, (row_num, col_num))
    y = i.astype(data_type)
    print('\n',y)
    
my_func_2(1, 10, 3, 5, np.int8)
my_func_2(10, 100, 10, 10, np.float64)   



 [[0.22216944 0.79250177 0.71845672 0.0802274 ]
 [0.42568594 0.55224897 0.9925371  0.35061385]]

 [[8 6 7 1 3]
 [3 2 7 4 6]
 [9 9 7 4 4]]

 [[82.70021956 44.79306353 77.97396123 61.42045161 29.92393051 88.10571445
  73.62956479 51.88656591 80.62951895 94.47753051]
 [49.5112941  89.54678761 97.1355553  23.55886089 64.66972011 11.46155334
  81.6313777  23.59063265 66.49603779 63.36107766]
 [73.85366745 77.87422746 74.00208107 53.23369196 38.42848481 44.5651734
  15.64042179 68.51611602 52.58251686 15.45268326]
 [76.01552483 49.44486061 57.33422012 47.62715198 84.15723537 70.7266246
  55.19155227 48.49583244 97.53651065 60.40278859]
 [22.89834661 43.02667088 74.57363948 58.5732175  92.3011283  99.72160659
  99.54413505 84.18327416 62.7545348  61.21181441]
 [51.3837132  27.80886227 83.46062989 91.34496028 84.45771752 48.79172366
  95.02348938 94.99814391 76.35197767 42.83070692]
 [16.33495227 76.966279   74.2063242  55.51629811 57.65954222 93.18941412
  95.75581983 57.19157929 91.09211501

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [122]:
import csv
import numpy as np


In [162]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# Use this function to actually open the data inside of a NDArray
def open_csv(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0, 27), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = open_csv('redsox_2017_hitting.txt')
bs2018 = open_csv('redsox_2018_hitting.txt')

# SLG = (singles + doubles*2 + triples*3 + homeruns*4) / at-bats

# 2017
total_ab_2017 = sum(bs2017['AB'])
total_1b_2017 = sum(bs2017['H']) - sum(bs2017['2B']) - sum(bs2017['3B']) - sum(bs2017['HR'])
total_2b_2017 = sum(bs2017['2B']) * 2
total_3b_2017 = sum(bs2017['3B']) * 3
total_hr_2017 = sum(bs2017['HR']) * 4

# 2018
total_ab_2018 = sum(bs2018['AB'])
total_1b_2018 = sum(bs2018['H']) - sum(bs2018['2B']) - sum(bs2018['3B']) - sum(bs2018['HR'])
total_2b_2018 = sum(bs2018['2B']) * 2
total_3b_2018 = sum(bs2018['3B']) * 3
total_hr_2018 = sum(bs2018['HR']) * 4

# Team SLG Calculations
slg_2017 = (total_1b_2017 + total_2b_2017 + total_3b_2017 + total_hr_2017) / total_ab_2017
slg_2018 = (total_1b_2018 + total_2b_2018 + total_3b_2018 + total_hr_2018) / total_ab_2018

print(f"The total SLG percentage for the 2017 Boston Red Sox was {slg_2017}.")
print(f"The total SLG percentage for the 2018 Boston Red Sox was {slg_2018}.")

# Final Comparison and Output
if slg_2017 > slg_2018:
    print("\nWhen comparing 2017 and 2018, the Boston Red Sox had a better year in 2017 based on SLG percentage.")
else:
    print("\nWhen comparing 2017 and 2018, the Boston Red Sox had a better year in 2018 based on SLG percentage.")

The total SLG percentage for the 2017 Boston Red Sox was 0.4076500796883301.
The total SLG percentage for the 2018 Boston Red Sox was 0.4539614561027837.

When comparing 2017 and 2018, the Boston Red Sox had a better year in 2018 based on SLG percentage.
